// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPRaB40FjEGsMcKiw43tdWC6ZywnRfBAE',
    appId: '1:756571055032:web:ce71f7755042119a16254d',
    messagingSenderId: '756571055032',
    projectId: 'chat-app-9c187',
    authDomain: 'chat-app-9c187.firebaseapp.com',
    storageBucket: 'chat-app-9c187.appspot.com',
    measurementId: 'G-CW0FHLL66M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9YZvX7pN6qCHKBnLVAUmh9ziYP9BARd0',
    appId: '1:756571055032:android:b7c531bc596f2f5216254d',
    messagingSenderId: '756571055032',
    projectId: 'chat-app-9c187',
    storageBucket: 'chat-app-9c187.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLhmKHVX51PWbIHopGJh2a66XNQS47sbY',
    appId: '1:756571055032:ios:4708128be8f48b5216254d',
    messagingSenderId: '756571055032',
    projectId: 'chat-app-9c187',
    storageBucket: 'chat-app-9c187.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLhmKHVX51PWbIHopGJh2a66XNQS47sbY',
    appId: '1:756571055032:ios:4708128be8f48b5216254d',
    messagingSenderId: '756571055032',
    projectId: 'chat-app-9c187',
    storageBucket: 'chat-app-9c187.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPRaB40FjEGsMcKiw43tdWC6ZywnRfBAE',
    appId: '1:756571055032:web:e15541af4d8368c716254d',
    messagingSenderId: '756571055032',
    projectId: 'chat-app-9c187',
    authDomain: 'chat-app-9c187.firebaseapp.com',
    storageBucket: 'chat-app-9c187.appspot.com',
    measurementId: 'G-JPH8E5ZXL6',
  );
}
